### ISSUE TITLE
Fix AUR package

### ISSUE THREAD

**Issue by flying-sheep** [itsmeow/spicetify-cli-update#1]
Hi, you seem to have missed my comment on the AUR: https://aur.archlinux.org/packages/spicetify-cli#comment-911696

Please fix the version!

**Comment by itsmeow** [comment]
Maaan AUR sucks

**Comment by flying-sheep** [comment]
what do you mean? because you didn’t get a notification?

**Comment by itsmeow** [comment]
Fixed this, forgot to close.
I say it sucks because I do not understand it - but that is my problem. I don't use arch.
